### ISSUE TITLE
Add media section

### ISSUE THREAD

**Issue by sdelquin** [sdelquin/sendhereplz.com#3]
It would be fine to add a Media Section, from where we can link the news published on media.
I figure it out as "mono" logos with a link...

![400px-Logo_de_Televisión_Canaria svg](https://user-images.githubusercontent.com/1591599/92148922-2757a280-ee15-11ea-8ea3-1ef091fdb9a1.png) with a link to the video...

**Comment by Pustur** [comment]
I pushed a draft of the media section at this commit: https://github.com/Pustur/sendhereplz.com/commit/a05c65d96af828728be715e3386aa1e548854eb6

If anyone wants to use it as a starting point feel free to do so.  
Otherwise I could continue myself (If you like how it looks) but I need all the logos and links that need to be inserted.

Here's how it looks so far:
<img width="1065" alt="screenshot" src="https://user-images.githubusercontent.com/13663338/92419590-c5799e80-f16e-11ea-811f-0e24809c8424.png">

**Comment by sdelquin** [comment]
Hey @Pustur,

This is exactly what I had in mind. So far, we have the following media:

**Diario de avisos**

LOGO: https://diariodeavisos.elespanol.com/img/estaticos/da_default.png
LINK: https://diariodeavisos.elespanol.com/2020/08/esta-extension-chrome-ahorrara-horas-busqueda-amazon-compras-desde-canarias/

**Televisión Canaria**

LOGO: https://es.wikipedia.org/wiki/Archivo:Logo_de_Televisi%C3%B3n_Canaria.svg
LINK: https://youtu.be/PQ5oQaO_w5Q?t=2414
